# Copy into git ignored *config.yml file and enter your own details
---
name: Copy_Data_Pipeline
provider:
  azureml:
    workspace:
      subscription_id: subscription_id
      resource_group: resource_group
      workspace_name: workspace_name
    compute_name: cluster
jobs:
- copy_data1:
    code:
      folder: examples/copy_data_scripts
      main: main.py
    inputs:
    - input_data
    outputs:
    - pipeline_data
    parameters:
      input_file: test.txt # Pre-existing file in your input datastore
      output_file: test1.txt # File to create in your output datastore
    environment: experiment_env
- copy_data2:
    code:
      folder: examples/copy_data_scripts
      main: main.py
    inputs:
    - pipeline_data
    - output_data
    parameters:
      input_file: test1.txt
      output_file: output2.txt
    environment: experiment_env
data:
  input_data:
    type: datareference
    parameter_name: input_path
    mount_path: /
    datastore:
      name: input_datastore
  output_data:
    type: datareference
    parameter_name: output_path
    mount_path: /
    datastore:
      name: output_datastore
  pipeline_data:
    type: pipelinedata
    input_parameter_name: input_path
    output_parameter_name: output_path
    datastore:
      name: output_datastore
environments:
  experiment_env:
    name: experiment_env
    dependencies:
    - python=3.7
    - pip:
      - azureml-defaults
